### PR TITLE
Add test_depends/test_uses

### LINKED ISSUE #48: [FEATURE] Replace `test_driver` with a generic solution
**Describe the scenario and circumstances that should be addressed**

`dds` gives special privilege to a "test-driver" library, which is currently only Catch2, and only the version that it ships. The way it links and uses the test-driver is also convoluted and slows the build.

**Describe the solution you'd like**

Allow a "test_uses" and "test_depends" so that a project can declare libraries that should be only available to tests, and do not act as transitive dependencies for its dependees.

**Additional context**

This will require that `dds` is able to load a different set of usage requirements for its `.test.c[pp]` files than for the other compiled files.

### PR DESCRIPTION
**Pull request by Quincunx271**
Closes #48 

This is still a WIP. ~~I think it works, but~~ I may have committed some atrocities in the code.

I plan on refactoring and on rewriting the commit history to something reasonable.

Edit: There are some bugs or things that I have yet to implement, as evidenced by the failing tests I've added.

### CODE REVIEW

**Comment by Quincunx271** [comment]
Something I'm realizing that I'm realizing I'll need to address is what should happen on mixed usage requirements (e.g. `depends: [ ... ]` in package.json5, but `test_uses: [ ... ]` in the library.json5). At a minimum, I need to add tests for those cases.

**Comment by vector-of-bool** [comment]
```diff
diff --git a/tools/dds_ci/testing/fixtures.py b/tools/dds_ci/testing/fixtures.py
index 11e0d93b..0d5dc21d 100644
--- a/tools/dds_ci/testing/fixtures.py
+++ b/tools/dds_ci/testing/fixtures.py
@@ -246,8 +246,12 @@ def dds_exe(pytestconfig: PyTestConfig) -> Path:
     return Path(opt)
 
 
+TmpGitRepoFactory = Callable[[Pathish], Path]
+
+
 @pytest.fixture
-def tmp_git_repo_factory(tmp_path_factory: TempPathFactory, request: FixtureRequest, pytestconfig: PyTestConfig) -> Callable[[str], Path]:
+def tmp_git_repo_factory(tmp_path_factory: TempPathFactory, request: FixtureRequest,
+                         pytestconfig: PyTestConfig) -> TmpGitRepoFactory:
     """
     A temporary directory :class:`pathlib.Path` object in which a git repo will
     be initialized
@@ -255,23 +259,24 @@ def tmp_git_repo_factory(tmp_path_factory: TempPathFactory, request: FixtureRequ
 
     test_dir = Path(request.fspath).parent
 
-    def f(dirpath) -> Path:
+    def f(dirpath: Pathish) -> Path:
         dirpath = Path(dirpath)
         if not dirpath.is_absolute():
             dirpath = test_dir / dirpath
 
         tmp_path = tmp_path_factory.mktemp('tmp-git')
-
-        shutil.copytree(dirpath, tmp_path, dirs_exist_ok=True)
+        # Could use dirs_exists_ok=True with Python 3.8, but we min dep on 3.6
+        repo = tmp_path / 'r'
+        shutil.copytree(dirpath, repo)
 
         git = pytestconfig.getoption('--git-exe') or 'git'
-        check_run([git, 'init', str(tmp_path)])
-        check_run([git, 'checkout', '-b', 'tmp_git_repo'], cwd=str(tmp_path))
-        check_run([git, 'add', '-A'], cwd=str(tmp_path))
-        check_run([git, '-c', "user.name='Tmp Git'",
-                   '-c', "user.email='dds@example.org'",
-                   'commit', '-m', 'Initial commit'], cwd=str(tmp_path))
-
-        return tmp_path
+        check_run([git, 'init', repo])
+        check_run([git, 'checkout', '-b', 'tmp_git_repo'], cwd=repo)
+        check_run([git, 'add', '-A'], cwd=repo)
+        check_run(
+            [git, '-c', "user.name='Tmp Git'", '-c', "user.email='dds@example.org'", 'commit', '-m', 'Initial commit'],
+            cwd=repo)
+
+        return repo
 
     return f

```

**Comment by vector-of-bool** [comment]
```diff
diff --git a/src/dds/cli/cmd/build_common.cpp b/src/dds/cli/cmd/build_common.cpp
index 1ae97161..9cc87b5b 100644
--- a/src/dds/cli/cmd/build_common.cpp
+++ b/src/dds/cli/cmd/build_common.cpp
@@ -4,6 +4,7 @@
 #include <dds/pkg/cache.hpp>
 #include <dds/pkg/db.hpp>
 #include <dds/pkg/get/get.hpp>
+#include <dds/util/algo.hpp>
 
 #include <boost/leaf/handle_exception.hpp>
 
@@ -32,24 +33,17 @@ builder dds::cli::create_project_builder(const dds::cli::options& opts) {
             pkg_cache_flags::write_lock | pkg_cache_flags::create_if_absent,
             [&](pkg_cache repo) {
                 // Download dependencies
-                auto deps      = repo.solve(man.dependencies, cat);
-                auto test_deps = repo.solve(man.test_dependencies, cat);
+                auto all_deps = man.dependencies;
+                extend(all_deps, man.test_dependencies);
+                auto deps = repo.solve(all_deps, cat);
                 get_all(deps, repo, cat);
-                get_all(test_deps, repo, cat);
 
-                const auto add_pkg = [&](const pkg_id& pk) {
-                    auto sdist_ptr = repo.find(pk);
+                for (const pkg_id& pkg : deps) {
+                    auto sdist_ptr = repo.find(pkg);
                     assert(sdist_ptr);
                     sdist_build_params deps_params;
                     deps_params.subdir = fs::path("_deps") / sdist_ptr->manifest.id.to_string();
                     builder.add(*sdist_ptr, deps_params);
-                };
-
-                for (const pkg_id& pk : deps) {
-                    add_pkg(pk);
-                }
-                for (const pkg_id& pk : test_deps) {
-                    add_pkg(pk);
                 }
             });
     }

```

**Comment by vector-of-bool** [comment]
```diff
diff --git a/src/dds/deps.cpp b/src/dds/deps.cpp
index 519ab2ef..59ae3fdb 100644
--- a/src/dds/deps.cpp
+++ b/src/dds/deps.cpp
@@ -54,6 +54,12 @@ dependency_manifest dependency_manifest::from_file(path_ref fpath) {
 
     dependency_manifest depman;
     using namespace semester::walk_ops;
+    // Helpers
+    using require_array  = require_type<json5::data::array_type>;
+    using require_string = require_type<std::string>;
+    auto str_as_dep = [](const std::string& str) { return dependency::parse_depends_string(str); };
+    auto append_dep = put_into(std::back_inserter(depman.dependencies), str_as_dep);
+    // Parse and validate
     auto res = walk.try_walk(  //
         data,
         require_type<json5::data::mapping_type>{
@@ -62,27 +68,16 @@ dependency_manifest dependency_manifest::from_file(path_ref fpath) {
             required_key{
                 "depends",
                 "A 'depends' key is required",
-                require_type<json5::data::array_type>{"'depends' must be an array of strings"},
-                for_each{
-                    require_type<std::string>{"Each dependency should be a string"},
-                    put_into(std::back_inserter(depman.dependencies),
-                             [](const std::string& str) {
-                                 return dependency::parse_depends_string(str);
-                             }),
-                },
+                require_array{"'depends' must be an array of strings"},
+                for_each{require_string{"Each dependency in 'depends' should be a string"},
+                         append_dep},
+            },
+            if_key{
+                "test_depends",
+                require_array("'test_depends' must be an array of strings"),
+                for_each{require_string("Each dependency in 'test_depends' should be a string"),
+                         append_dep},
             },
-            if_key{"test_depends",
-                   [&](auto&& dat) {
-                       if (!dat.is_array()) {
-                           return walk.reject(
-                               "'test_depends' should be an array of dependency strings");
-                       }
-
-                       return for_each{put_into{std::back_inserter(depman.test_dependencies),
-                                                [](const std::string& depstr) {
-                                                    return dependency::parse_depends_string(depstr);
-                                                }}}(dat);
-                   }},
         });
 
     res.throw_if_rejected<user_error<errc::invalid_pkg_manifest>>();
diff --git a/src/dds/sdist/library/manifest.cpp b/src/dds/sdist/library/manifest.cpp
index cce63178..6416bb70 100644
--- a/src/dds/sdist/library/manifest.cpp
+++ b/src/dds/sdist/library/manifest.cpp
@@ -28,6 +28,11 @@ library_manifest library_manifest::load_from_file(path_ref fpath) {
 
     library_manifest lib;
     using namespace semester::walk_ops;
+    // Helpers
+    auto str_to_usage = [](const std::string& s) { return lm::split_usage_string(s); };
+    auto append_usage
+        = [&](auto& usages) { return put_into(std::back_inserter(usages), str_to_usage); };
+    // Parse and validate
     walk(data,
          require_obj{"Root of library manifest should be a JSON object"},
          mapping{
@@ -40,13 +45,11 @@ library_manifest library_manifest::load_from_file(path_ref fpath) {
              if_key{"uses",
                     require_array{"'uses' must be an array of strings"},
                     for_each{require_str{"Each 'uses' element should be a string"},
-                             put_into{std::back_inserter(lib.uses),
-                                      [](std::string s) { return lm::split_usage_string(s); }}}},
+                             append_usage(lib.uses)}},
              if_key{"test_uses",
                     require_array{"'test_uses' must be an array of strings"},
                     for_each{require_str{"Each 'test_uses' element should be a string"},
-                             put_into(std::back_inserter(lib.test_uses),
-                                      [](std::string s) { return lm::split_usage_string(s); })}},
+                             append_usage(lib.test_uses)}},
          });
 
     return lib;
diff --git a/src/dds/sdist/package.cpp b/src/dds/sdist/package.cpp
index 6cc44359..95b99264 100644
--- a/src/dds/sdist/package.cpp
+++ b/src/dds/sdist/package.cpp
@@ -45,6 +45,9 @@ package_manifest parse_json(const json5::data& data, std::string_view fpath) {
         return walk.accept;
     };
 
+    auto str_to_dependency
+        = [](const std::string& s) { return dependency::parse_depends_string(s); };
+
     walk(data,
          require_obj{"Root of package manifest should be a JSON object"},
          mapping{
@@ -80,27 +83,17 @@ package_manifest parse_json(const json5::data& data, std::string_view fpath) {
                             return mapping{push_depends_obj_kv}(dat);
                         } else if (dat.is_array()) {
                             return for_each{put_into{std::back_inserter(ret.dependencies),
-                                                     [](const std::string& depstr) {
-                                                         return dependency::parse_depends_string(
-                                                             depstr);
-                                                     }}}(dat);
+                                                     str_to_dependency}}(dat);
                         } else {
                             return walk.reject(
                                 "'depends' should be an array of dependency strings");
                         }
                     }},
              if_key{"test_depends",
-                    [&](auto&& dat) {
-                        if (!dat.is_array()) {
-                            return walk.reject(
-                                "'test_depends' should be an array of dependency strings");
-                        }
-
-                        return for_each{put_into{std::back_inserter(ret.test_dependencies),
-                                                 [](const std::string& depstr) {
-                                                     return dependency::parse_depends_string(
-                                                         depstr);
-                                                 }}}(dat);
+                    require_array{"'test_depends' should be an array of dependency strings"},
+                    for_each{
+                        require_str{"Each of 'test_depends' should be a string"},
+                        put_into{std::back_inserter(ret.test_dependencies), str_to_dependency},
                     }},
              if_key{"test_driver",
                     require_str{"'test_driver' must be a string"},

```

**Comment by vector-of-bool** [comment]
(I'm reviewing via the VSCode plugin, so some comments/suggestions may be kind of goofy.)

**Comment by vector-of-bool** [comment]
Don't worry about the case of `test_depends_but_regular_uses`. There's an upcoming ticket to merge the package and library manifest files, and that will also merge the `deps` and `uses` attributes, thereby preventing this issue.

**Comment by Quincunx271** [comment]
> Don't worry about the case of `test_depends_but_regular_uses`. There's an upcoming ticket to merge the package and library manifest files, and that will also merge the `deps` and `uses` attributes, thereby preventing this issue.

Okay, but to be clear, I _should_ worry about it in the multi-libs case? Because you can have your `package.json` and multiple `library.json` under the libs/ directory.

**Comment by vector-of-bool** [comment]
I'm still considering a single top-level package.json in the case of multiple library roots. It will require a more complex schema in the json file, but I think the simplicity is worth it. How that will look is still TBD. It'll be resolved before the beta release, though.

**Comment by Quincunx271** [comment]
> (I'm reviewing via the VSCode plugin, so some comments/suggestions may be kind of goofy.)

Idk if I'm doing something wrong, but I opened this PR in VSCode and tried to "Apply Patch" your suggestions, but none of the patches "apply."  Trying `git apply --3way the-patch.patch` doesn't work either (fails with `error: repository lacks the necessary blob to fall back on 3-way merge.`). If you know what I'm doing wrong, please advise.

Meanwhile, I'll probably just apply the suggestions manually

**Comment by Quincunx271** [comment]
> `auto append_dep = put_into(std::back_inserter(depman.dependencies), str_as_dep);`

Is there a reason why you're suggesting to always insert into `depman.dependencies` and never to `depman.test_dependencies` (in deps.cpp)? Is it that the `test_dependencies` is unneeded? Or should this be like the `append_usages` in manifest.cpp (this is what I did in the latest commit).

I'm still going to go back through the code because I'm not convinced I implemented this correctly, but I wanted to check if that suggestion is some insight that I'm missing.

**Comment by vector-of-bool** [comment]
> Idk if I'm doing something wrong, but I opened this PR in VSCode and tried to "Apply Patch" your suggestions, but none of the patches "apply."

AFAIK, that should 'just work." Possibly a bug in the VSC extension?

> Is there a reason why you're suggesting ...

No, probably just a typo on my part.

I think your changes look pretty good, other than the few nits I pointed out.

**Comment by Quincunx271** [comment]
Remaining concern: many testing frameworks expect that the user has a main test file in which they define main, e.g. Catch2 has its `CATCH_CONFIG_MAIN` expectation. This alone would be okay, because we could just use a `Catch-With-Main` library. However, this runs into issues when you want to do custom configuration of main.

For example, I've had code similar to this in the past:

```c++
#define CATCH_CONFIG_RUNNER
#include <catch2/catch.hpp>

#include <QApplication>

int main(int argc, char** argv) {
    QApplication app(argc, argv);
    return Catch::Session().run(argc, argv);
}
```

Thus the question: how do we support test library configuration? If the library supports tweaks headers, this would be a reasonable use of tweak headers, but most libraries don't use that model of configuration.

At any rate, it's probably not something we have to consider in this PR considering we didn't support that before, but this is definitely something that should be figured out.

**Comment by Quincunx271** [comment]
Alright, I've made the changes and cleaned up the commit history.

**Comment by vector-of-bool** [comment]
The answer is to tweak the `test_uses` to refer to a library that implements the part you want. In order to support that, the Catch sdist will need to be tweaked to add some additional libraries. For example, a `catch2/catch2` library that is *just* Catch2, a `catch2/main` library that contains a definition of `main()`, a `catch2/runner` library that contains just the runner, etc.

I'm working on a new project that will contain various scripts that perform such modifications programmatically before posting them to the repository.

**Review by vector-of-bool — APPROVED** [review]

**Pull request merged**
