### PR TITLE
Support GNU extensions

### PR DESCRIPTION
**Pull request by thevisus**
## Existing Behavior and Potential Problems

`dds` support for [specifying C and C++ language version](https://dds.pizza/docs/guide/toolchains.html#c-version-and-cxx-version) is complete with regard to each language's available standards. This is likely (ideally) sufficient for new projects, but in practice there are many many existing codebases and libraries that use GNU extensions. I know this is particularly true in the embedded world, as GCC historically was typically the first (or only) compiler for a given vendor's hardware.

Regardless, in my effort to setup several embedded projects with `dds` I needed to enable GNU extensions for a majority of third-party libraries. Additionally, I discovered that `dds` did not respect asm source files for compilation or packaging, which precluded packaging a swath of libraries as many are prone to writing chunks in asm alongside C/C++ files.

### multiple -std
My initial stab at the language version problem was to simply add the appropriate `-std=gnuXYZ` to the compilation `flags`. This didn't work because `dds` requires a `c_version`/`cxx_version` in the toolchain *and* emits that flag in addition to those in any `flags` options. As GCC accepts multiple `-std` flags - a "feature" which has certainly been abused - the behavior of `dds` is sane. However, since the *ordering* of any `-std` flags affects the selected feature-set, it's unreliable and should be discouraged IMO. In my tests, `dds` emits the `-std=cXYZ` flag last, which was problematic for libraries I was packaging.

### empty -std
An alternative to adding the `gnuXYZ` variants to the `c_version`/`cxx_version` options is to allow an empty `c_version`/`cxx_version` so that a user could provide anything via the `flags` option(s) or rely on compiler defaults. Personally, I think relying on defaults or allowing an invalid option specification is sloppy at best and introducing unexpected bugs at worst. Explicit & enforceable specification is preferable.

### .S/.s
Although asm is technically (nay, the epitome of) source code, I'm not terribly pleased with treating `.S` as a dds "source" file. asm and corresponding tools & options for linking/optimizing/etc are highly platform-centric; worse yet, it's source that often coexists with source from another language and is intended to be distributed & built simultaneously. `dds` toolchains don't provide a whole lot of knobs (thankfully), so asm becomes a sort of "wedge it in there" necessity.

I don't know of a better alternative than my simple `file.cpp` change without spending a lot more time on it. Since the `dds` design is explicitly built on *source distribution*, one could not simply archive the asm files for distribution with a set of headers. Therefore, preserving these files, passing them to the toolchain, and packaging them up just like every other one seems sensible.

### CODE REVIEW

**Comment by vector-of-bool** [comment]
I was actually planning on changing the way language-version flags are passed through the toolchain, and have another "advanced" toolchain option like this:

```js
{
  // ...
  advanced: {
    version_flag_template: '-std=[version]'  // Default for GNU-like
    version_flag_template: '/std:[version]'  // Default for MSVC
  }
}
```

and instead the `cxx_version` and `c_version` flags would be just be arbitrary strings inserted in place of `[version]`. This would allow for `/std:c++latest` on MSVC by just setting `cxx_version` to `c++latest`, which does not have a fixed version. This would also automatically allow for GNU extended language versions as well.

**Comment by vector-of-bool** [comment]
Also, regarding ASM: I've thought about it, but it hasn't yet come up. I want `dds` to be able to run an assembler as well as compilers, and it should be possible by just adding some more toolchain options and more `asm` "language" options and features (e.g. `asm_flags`).

Simply adding them and passing them to the C++ compiler should "just work" for now, and I'll accept such a change for now, but it will require more changes to be fully complete in the future. (e.g. That won't work with MSVC, where the assembler is a different executable entirely.)

**Comment by vector-of-bool** [comment]
I've created a new changeset in #70 that I think offers a more generalized and future-proof solution to setting language versions. As for supporting assembly source files, that will require a separate changeset.

**Comment by thevisus** [comment]
I'm terribly sorry to have been unable to tend to this for so long. I like your updates in the other changeset and that works great for the needs I have.

Regarding asm, separate toolchain options would provide more complete and sustainable control over how they are built within & in combination with other packages. I may re-submit the ".S" change separately, as simply including them in a package for distribution is sufficient for me (for now) to wrangle them in the final build.

**Pull request closed without merging**
